### Get Orders

GET http://localhost:4004/odata/v4/manage-orders/Orders

### Get Orders Params
GET http://localhost:4004/odata/v4/manage-orders/Orders('cliente2@gmail.com')

### 3 Create Orders

POST  http://localhost:4004/odata/v4/manage-orders/Orders HTTP/1.1
Content-Type: application/json

{
    "ClientEmail": "client9@gmail.com",
    "FirstName": "Guillermo",
    "LastName": "Quattrocchi",
    "CreatedOn": "2021-05-22"
}


### Update Orders

PUT http://localhost:4004/odata/v4/manage-orders/Orders('cliente2@gmail.com') HTTP/1.1
Content-Type: application/json

{
    "FirstName": "Julian",
"LastName": "Tapia"
}

### Delete Order

DELETE  http://localhost:4004/odata/v4/manage-orders/Orders('cliente3@gmail.com') HTTP/1.1


### GetTaxes

GET http://localhost:4004/odata/v4/manage-orders/getClientTaxRate(clientEmail='cliente3@gmail.com')


### Cancel order ACTION

POST http://localhost:4004/odata/v4/manage-orders/cancelOrder
Content-Type: application/json

{
"clientEmail": "cliente3@gmail.com"
}


### GetTaxes Function Bound

GET http://localhost:4004/odata/v4/manage-orders/Orders('cliente1@gmail.com')/ManageOrders.getClientTaxRate(clientEmail='cliente3@gmail.com')


### Cancel order ACTION Bound

POST http://localhost:4004/odata/v4/manage-orders/Orders('cliente3@gmail.com')/ManageOrders.cancelOrder
Content-Type: application/json

{
"clientEmail": "cliente3@gmail.com"
}


### Get Products

GET http://localhost:4004/odata/v4/sapbackend-exit/Products